version: "3.9"
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
        restart: on-failure

    backend-app:
        image: vaidhyesh/sample-express-server:latest
        container_name: backend-app
        environment:
            - DB_SERVER=mongodb
            - MONGO_PORT=27017
            - MONGO_USER=root
            - MONGO_PASSWORD=password
        ports:
            - 8080:3000
        links:
        - mongodb
volumes:
  mongodb: