# This is a basic workflow to help you get started with Actions

name: CICD for pushing docker images

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: docker/build-push-action@v2


      # Runs a set of commands using the runners shell
      - name: Build and deploy docker build to docker hub
        run: |
          echo Building docker image
          docker build . -t vaidhyesh/sample-express-server
          echo Pushing docker image to docker-hub
          docker push vaidhyesh/sample-express-server:latest
          echo removing Docker image
          docker rmi vaidhyesh/sample-express-server
          
